//generated using http://phrogz.net/css/distinct-colors.html

export const HOSPITAL_COLORS =
 {
  "DRK Kliniken Berlin | Westend": "#bf8f8f", 
  "Martin-Luther-Krankenhaus": "#ff2200", 
  "Sankt Gertrauden-Krankenhaus": "#330e00", 
  "Schlosspark-Klinik": "#994526", 
  "Vivantes - Klinikum Am Urban": "#ff8c40", 
  "Vivantes - Klinikum im Friedrichshain - Standort Landsberger Allee": "#593000", 
  "Evangelisches Krankenhaus Königin Elisabeth Herzberge": "#bfa98f", 
  "Sana Klinikum Lichtenberg": "#b27700", 
  "Unfallkrankenhaus Berlin": "#665c33", 
  "Vivantes - Klinikum Kaulsdorf": "#a7b300", 
  "Bundeswehrkrankenhaus Berlin": "#fbffbf", 
  "Charité - Campus Charité Mitte": "#224000", 
  "Charité - Campus Virchow-Klinikum": "#73ff40", 
  "DRK Kliniken Berlin | Mitte": "#79bf60", 
  "Evangelische Elisabeth Klinik": "#263328", 
  "Franziskus-Krankenhaus": "#7ca692",
  "Jüdisches Krankenhaus Berlin": "#00734d", 
  "St. Hedwig-Kliniken Berlin - St. Hedwig-Krankenhaus": "#40ffbf", 
  "Vivantes - Klinikum Neukölln": "#007780", 
  "HELIOS Klinikum Berlin-Buch": "#40f2ff", 
  "Maria Heimsuchung, Caritas-Klinik Pankow": "#002933", 
  "Park-Klinik Weißensee": "#005580", 
  "Dominikus-Krankenhaus": "#40bfff", 
  "Vivantes - Humboldt-Klinikum": "#69818c", 
  "Evangelisches Waldkrankenhaus Spandau": "#0066ff", 
  "Gemeinschaftskrankenhaus Havelhöhe": "#002459", 
  "Vivantes - Klinikum Spandau": "#606cbf", 
  "Charité - Campus Benjamin Franklin": "#c8bfff", 
  "Evangelisches Krankenhaus Hubertus": "#6600ff", 
  "HELIOS Klinikum Emil von Behring": "#38008c", 
  "Krankenhaus Bethel Berlin": "#f780ff", 
  "Krankenhaus Waldfriede": "#40003c", 
  "St. Marien-Krankenhaus Berlin": "#99007a", 
  "St. Joseph-Krankenhaus (Tempelhof)": "#806079", 
  "Vivantes - Auguste-Viktoria-Klinikum": "#331a27", 
  "Vivantes - Wenckebach-Klinikum": "#ff80b3", 
  "DRK Kliniken Berlin | Köpenick": "#ff4059", 
  "St. Hedwig-Kliniken Berlin - Krankenhaus Hedwigshöhe": "#7f202d",
 }
